// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fitness.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Fitness struct {
	AverageFitness       []float32 `protobuf:"fixed32,1,rep,name=AverageFitness" json:"AverageFitness,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Fitness) Reset()         { *m = Fitness{} }
func (m *Fitness) String() string { return proto.CompactTextString(m) }
func (*Fitness) ProtoMessage()    {}
func (*Fitness) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ffd2257217c4c17, []int{0}
}

func (m *Fitness) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fitness.Unmarshal(m, b)
}
func (m *Fitness) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fitness.Marshal(b, m, deterministic)
}
func (m *Fitness) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fitness.Merge(m, src)
}
func (m *Fitness) XXX_Size() int {
	return xxx_messageInfo_Fitness.Size(m)
}
func (m *Fitness) XXX_DiscardUnknown() {
	xxx_messageInfo_Fitness.DiscardUnknown(m)
}

var xxx_messageInfo_Fitness proto.InternalMessageInfo

func (m *Fitness) GetAverageFitness() []float32 {
	if m != nil {
		return m.AverageFitness
	}
	return nil
}

func init() {
	proto.RegisterType((*Fitness)(nil), "main.Fitness")
}

func init() { proto.RegisterFile("fitness.proto", fileDescriptor_2ffd2257217c4c17) }

var fileDescriptor_2ffd2257217c4c17 = []byte{
	// 74 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xcb, 0x2c, 0xc9,
	0x4b, 0x2d, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53,
	0x32, 0xe4, 0x62, 0x77, 0x83, 0x08, 0x0b, 0xa9, 0x71, 0xf1, 0x39, 0x96, 0xa5, 0x16, 0x25, 0xa6,
	0xa7, 0x42, 0x45, 0x24, 0x18, 0x15, 0x98, 0x35, 0x98, 0x82, 0xd0, 0x44, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xf2, 0x6d, 0x98, 0x9f, 0x48, 0x00, 0x00, 0x00,
}
