# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fitness.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fitness.proto',
  package='main',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rfitness.proto\x12\x04main\"!\n\x07\x46itness\x12\x16\n\x0e\x41verageFitness\x18\x01 \x03(\x02')
)




_FITNESS = _descriptor.Descriptor(
  name='Fitness',
  full_name='main.Fitness',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AverageFitness', full_name='main.Fitness.AverageFitness', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=56,
)

DESCRIPTOR.message_types_by_name['Fitness'] = _FITNESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Fitness = _reflection.GeneratedProtocolMessageType('Fitness', (_message.Message,), dict(
  DESCRIPTOR = _FITNESS,
  __module__ = 'fitness_pb2'
  # @@protoc_insertion_point(class_scope:main.Fitness)
  ))
_sym_db.RegisterMessage(Fitness)


# @@protoc_insertion_point(module_scope)
