// Code generated by protoc-gen-go. DO NOT EDIT.
// source: genom.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Genoms struct {
	Genoms               []uint64 `protobuf:"varint,1,rep,name=genoms" json:"genoms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Genoms) Reset()         { *m = Genoms{} }
func (m *Genoms) String() string { return proto.CompactTextString(m) }
func (*Genoms) ProtoMessage()    {}
func (*Genoms) Descriptor() ([]byte, []int) {
	return fileDescriptor_68891e2f1b91b663, []int{0}
}

func (m *Genoms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Genoms.Unmarshal(m, b)
}
func (m *Genoms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Genoms.Marshal(b, m, deterministic)
}
func (m *Genoms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Genoms.Merge(m, src)
}
func (m *Genoms) XXX_Size() int {
	return xxx_messageInfo_Genoms.Size(m)
}
func (m *Genoms) XXX_DiscardUnknown() {
	xxx_messageInfo_Genoms.DiscardUnknown(m)
}

var xxx_messageInfo_Genoms proto.InternalMessageInfo

func (m *Genoms) GetGenoms() []uint64 {
	if m != nil {
		return m.Genoms
	}
	return nil
}

type Creatures struct {
	Creatures            []*Genoms `protobuf:"bytes,1,rep,name=creatures" json:"creatures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Creatures) Reset()         { *m = Creatures{} }
func (m *Creatures) String() string { return proto.CompactTextString(m) }
func (*Creatures) ProtoMessage()    {}
func (*Creatures) Descriptor() ([]byte, []int) {
	return fileDescriptor_68891e2f1b91b663, []int{1}
}

func (m *Creatures) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Creatures.Unmarshal(m, b)
}
func (m *Creatures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Creatures.Marshal(b, m, deterministic)
}
func (m *Creatures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Creatures.Merge(m, src)
}
func (m *Creatures) XXX_Size() int {
	return xxx_messageInfo_Creatures.Size(m)
}
func (m *Creatures) XXX_DiscardUnknown() {
	xxx_messageInfo_Creatures.DiscardUnknown(m)
}

var xxx_messageInfo_Creatures proto.InternalMessageInfo

func (m *Creatures) GetCreatures() []*Genoms {
	if m != nil {
		return m.Creatures
	}
	return nil
}

func init() {
	proto.RegisterType((*Genoms)(nil), "main.Genoms")
	proto.RegisterType((*Creatures)(nil), "main.Creatures")
}

func init() { proto.RegisterFile("genom.proto", fileDescriptor_68891e2f1b91b663) }

var fileDescriptor_68891e2f1b91b663 = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4f, 0xcd, 0xcb,
	0xcf, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x52, 0xe0,
	0x62, 0x73, 0x07, 0x09, 0x16, 0x0b, 0x89, 0x71, 0xb1, 0x81, 0xa5, 0x8b, 0x25, 0x18, 0x15, 0x98,
	0x35, 0x58, 0x82, 0xa0, 0x3c, 0x25, 0x73, 0x2e, 0x4e, 0xe7, 0xa2, 0xd4, 0xc4, 0x92, 0xd2, 0xa2,
	0xd4, 0x62, 0x21, 0x2d, 0x2e, 0xce, 0x64, 0x18, 0x07, 0xac, 0x8e, 0xdb, 0x88, 0x47, 0x0f, 0x64,
	0x90, 0x1e, 0xc4, 0x94, 0x20, 0x84, 0x34, 0x20, 0x00, 0x00, 0xff, 0xff, 0x07, 0x7d, 0xa3, 0xe8,
	0x6e, 0x00, 0x00, 0x00,
}
